version: '3.8'

services:
  frontend:
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      VITE_API_URL: http://localhost:5000
    depends_on:
      - backend

  backend:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: mongodb://mongo:27017/yourdbname
      REDIS_URL: redis://redis:6379
      JWT_SECRET: supersecretkey
    depends_on:
      - mongo
      - redis

  mongo:
    container_name: mongo
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    container_name: redis
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  mongo-data:
